export const PAGE_SCROLL_WHEEL_DRAG_FACTOR = 1.00
export const PAGE_SCROLL_INERTIAL_LERP = 0.21
export const PAGE_SCROLL_MAX_WHEEL_DELTA = 660

export const GALLERY_SCROLL_WHEEL_DRAG_FACTOR = 0.64
export const GALLERY_SCROLL_INERTIAL_LERP = 0.126
export const GALLERY_SCROLL_MAX_WHEEL_DELTA = 420