export const PAGE_SCROLL_WHEEL_DRAG_FACTOR = 0.94
export const PAGE_SCROLL_INERTIAL_LERP = 0.196
export const PAGE_SCROLL_MAX_WHEEL_DELTA = 620

export const GALLERY_SCROLL_WHEEL_DRAG_FACTOR = 0.64
export const GALLERY_SCROLL_INERTIAL_LERP = 0.126
export const GALLERY_SCROLL_MAX_WHEEL_DELTA = 420

export const SCROLL_WHEEL_DRAG_FACTOR = 0.94
export const SCROLL_INERTIAL_LERP = 0.196
export const SCROLL_MAX_WHEEL_DELTA = 620